### ISSUE TITLE
command not found: yoke

### ISSUE THREAD

**Issue by cagartner** [yokessh/yoke#1]
Using elementary OS 0.3.2 Freya (64-bit)

Also, i do use zsh on command line, not sure if that's what made it conflict.

Cheers!

**Comment by cagartner** [comment]
![captura de tela de 2016-05-13 17 51 33](https://cloud.githubusercontent.com/assets/4007696/15261688/45b28df4-1934-11e6-8c3e-1d809939ea0f.png)

**Comment by hernandev** [comment]
It may happended because you didn't have the composer binary folder set on your PATH environment variable.

on your shell init script (in your case ~/.zshenv i guess)

add the following line:

```
export PATH=/home/carlos/.composer/vendor/bin:$PATH
```

And reopen the terminal. it should be enough to make composer binaries visible system wide

**Comment by cagartner** [comment]
Its work! Thank you.

**Comment by hernandev** [comment]
👍
